/*
 * This file has been auto-generated by CppUMockGen v0.5.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -t "#const CXCursor &=ConstPointer~&$" -t "@std::string=String" -t "#const std::string &=String~$.c_str()"
 */

#include "Constructor_expect.hpp"

namespace expect { namespace Constructor$ {
MockExpectedCall& Constructor$ctor()
{
    return Constructor$ctor(1);
}
MockExpectedCall& Constructor$ctor(unsigned int __numCalls__)
{
    MockExpectedCall& __expectedCall__ = mock().expectNCalls(__numCalls__, "Constructor::Constructor");
    return __expectedCall__;
}
} }

namespace expect { namespace Constructor$ {
MockExpectedCall& IsMockable(CppUMockGen::Parameter<const Constructor*> __object__, CppUMockGen::Parameter<const void*> cursor, bool __return__)
{
    return IsMockable(1, __object__, cursor, __return__);
}
MockExpectedCall& IsMockable(unsigned int __numCalls__, CppUMockGen::Parameter<const Constructor*> __object__, CppUMockGen::Parameter<const void*> cursor, bool __return__)
{
    bool __ignoreOtherParams__ = false;
    MockExpectedCall& __expectedCall__ = mock().expectNCalls(__numCalls__, "Constructor::IsMockable");
    if(!__object__.isIgnored()) { __expectedCall__.onObject(const_cast<Constructor*>(__object__.getValue())); }
    if(cursor.isIgnored()) { __ignoreOtherParams__ = true; } else { __expectedCall__.withConstPointerParameter("cursor", cursor.getValue()); }
    __expectedCall__.andReturnValue(__return__);
    if(__ignoreOtherParams__) { __expectedCall__.ignoreOtherParameters(); }
    return __expectedCall__;
}
} }

namespace expect { namespace Constructor$ {
MockExpectedCall& GetExpectationFunctionName(CppUMockGen::Parameter<const Constructor*> __object__, CppUMockGen::Parameter<const char*> functionName, const char* __return__)
{
    return GetExpectationFunctionName(1, __object__, functionName, __return__);
}
MockExpectedCall& GetExpectationFunctionName(unsigned int __numCalls__, CppUMockGen::Parameter<const Constructor*> __object__, CppUMockGen::Parameter<const char*> functionName, const char* __return__)
{
    bool __ignoreOtherParams__ = false;
    MockExpectedCall& __expectedCall__ = mock().expectNCalls(__numCalls__, "Constructor::GetExpectationFunctionName");
    if(!__object__.isIgnored()) { __expectedCall__.onObject(const_cast<Constructor*>(__object__.getValue())); }
    if(functionName.isIgnored()) { __ignoreOtherParams__ = true; } else { __expectedCall__.withStringParameter("functionName", functionName.getValue()); }
    __expectedCall__.andReturnValue(__return__);
    if(__ignoreOtherParams__) { __expectedCall__.ignoreOtherParameters(); }
    return __expectedCall__;
}
} }

