/*
 * This file has been auto-generated by CppUTestMock v0.3.0.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -t "#const std::string &=String/$.c_str()" 
 */

#include <CppUMockGen.h>

#include "ConsoleColorizer.hpp"

#include <CppUTestExt/MockSupport.h>

namespace expect { namespace ConsoleColorizer$ {
MockExpectedCall& SetColor(CppUMockGen::Parameter<const ConsoleColorizer*> __object__, CppUMockGen::Parameter<ConsoleColorizer::Color> color);
MockExpectedCall& SetColor(unsigned int __numCalls__, CppUMockGen::Parameter<const ConsoleColorizer*> __object__, CppUMockGen::Parameter<ConsoleColorizer::Color> color);
} }

