/*
 * This file has been auto-generated by CppUMockGen v0.5.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -t "#const CXCursor &=ConstPointer~&$"
 */

#include <CppUMockGen.hpp>

#include "Method.hpp"

#include <CppUTestExt/MockSupport.h>

namespace expect { namespace Method$ {
MockExpectedCall& Method$ctor();
MockExpectedCall& Method$ctor(unsigned int __numCalls__);
} }

namespace expect { namespace Method$ {
MockExpectedCall& IsMockable(CppUMockGen::Parameter<const Method*> __object__, CppUMockGen::Parameter<const void*> cursor, bool __return__);
MockExpectedCall& IsMockable(unsigned int __numCalls__, CppUMockGen::Parameter<const Method*> __object__, CppUMockGen::Parameter<const void*> cursor, bool __return__);
} }

