/*
 * This file has been auto-generated by CppUMockGen v0.5.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -t "#const CXCursor &=ConstPointer~&$"
 */

#include "Method_expect.hpp"

namespace expect { namespace Method$ {
MockExpectedCall& Method$ctor()
{
    return Method$ctor(1);
}
MockExpectedCall& Method$ctor(unsigned int __numCalls__)
{
    MockExpectedCall& __expectedCall__ = mock().expectNCalls(__numCalls__, "Method::Method");
    return __expectedCall__;
}
} }

namespace expect { namespace Method$ {
MockExpectedCall& IsMockable(CppUMockGen::Parameter<const Method*> __object__, CppUMockGen::Parameter<const void*> cursor, bool __return__)
{
    return IsMockable(1, __object__, cursor, __return__);
}
MockExpectedCall& IsMockable(unsigned int __numCalls__, CppUMockGen::Parameter<const Method*> __object__, CppUMockGen::Parameter<const void*> cursor, bool __return__)
{
    bool __ignoreOtherParams__ = false;
    MockExpectedCall& __expectedCall__ = mock().expectNCalls(__numCalls__, "Method::IsMockable");
    if(!__object__.isIgnored()) { __expectedCall__.onObject(const_cast<Method*>(__object__.getValue())); }
    if(cursor.isIgnored()) { __ignoreOtherParams__ = true; } else { __expectedCall__.withConstPointerParameter("cursor", cursor.getValue()); }
    __expectedCall__.andReturnValue(__return__);
    if(__ignoreOtherParams__) { __expectedCall__.ignoreOtherParameters(); }
    return __expectedCall__;
}
} }

