#include <iostream>
#include <fstream>
#include <clang-c/Index.h>
#include <cxxopts.hpp>
#include "Function.hpp"
#include "Method.hpp"
#include "Config.hpp"

std::ostream* output;

void parseFile( const std::string &input, const Config &config,  bool interpretAsCpp )
{
    CXIndex index = clang_createIndex( 0, 1 );

    std::vector<const char*> clangOpts;
    if( interpretAsCpp )
    {
        clangOpts.push_back( "-xc++" );
    }

    CXTranslationUnit tu = clang_parseTranslationUnit( index, input.c_str(),
                                                       clangOpts.data(), clangOpts.size(),
                                                       nullptr, 0,
                                                       CXTranslationUnit_None );
    if( tu == nullptr )
    {
        std::cerr << "Unable to parse translation unit. Quitting." << std::endl;
        exit(-1);
    }

    CXCursor tuCursor = clang_getTranslationUnitCursor(tu);
    clang_visitChildren(
        tuCursor,
        []( CXCursor cursor, CXCursor parent, CXClientData client_data )
        {
            if( clang_Location_isFromMainFile( clang_getCursorLocation( cursor ) ) != 0 )
            {
                CXCursorKind cursorKind = clang_getCursorKind( cursor );
                if( cursorKind == CXCursor_FunctionDecl )
                {
                    Function function( cursor, *(Config *)client_data );
                    if( function.IsMockable() )
                    {
                        *output << function.GenerateMock() << std::endl;
                    }
                    return CXChildVisit_Continue;
                }
                else if( cursorKind == CXCursor_CXXMethod )
                {
                    Method method( cursor, *(Config *)client_data );
                    if( method.IsMockable() )
                    {
                        *output << method.GenerateMock() << std::endl;
                    }
                    return CXChildVisit_Continue;
                }
                else
                {
                    //            std::cout << "Cursor '" << clang_getCursorSpelling( cursor ) << "' of kind '"
                    //                << clang_getCursorKindSpelling( clang_getCursorKind( cursor ) ) << "'\n";
                    return CXChildVisit_Recurse;
                }
            }
            else
            {
                return CXChildVisit_Continue;
            }
        },
        (CXClientData) &config );

    clang_disposeTranslationUnit( tu );
    clang_disposeIndex( index );
}

int main( int argc, char* argv[] )
{
    cxxopts::Options optionsConfig("CppUMockGen", "Mock generator for CppUTest");

    optionsConfig.add_options()
        ( "i,input", "Input file", cxxopts::value<std::string>(), "<input>" )
        ( "o,output", "Output file", cxxopts::value<std::string>(), "<output>" )
        ( "x,cpp", "Force interpretation of the input file as C++", cxxopts::value<bool>()->default_value(false), "<force-cpp>" )
        ( "u,underlying-typedef", "Use underlying typedef type", cxxopts::value<bool>()->default_value("false"), "[<underlying-typedef>]" )
        ( "h,help", "Print help" );

    optionsConfig.positional_help( "[<input>] [<output>]" );
    optionsConfig.parse_positional( std::vector<std::string> { "input", "output" } );

    cxxopts::ParseResult parsedOptions = optionsConfig.parse( argc, argv );

    if( parsedOptions.count("help") )
    {
        std::cout << optionsConfig.help() << std::endl;
        exit(0);
    }

    if( !parsedOptions.count( "input" ) )
    {
        std::cerr << "No input file specified" << std::endl;
        exit(1);
    }

    std::string inputFileName = parsedOptions["input"].as<std::string>();

    std::ofstream outputFile;

    if( !parsedOptions.count( "output" ) )
    {
        output = &std::cout;
    }
    else
    {
        outputFile.open( parsedOptions["output"].as<std::string>() );
        if( ! outputFile.is_open() )
        {
            std::cerr << "Error opening output file" << std::endl;
            exit(1);
        }
        output = &outputFile;
    }

    bool interpretAsCpp = false;
    if( parsedOptions["cpp"].as<bool>() )
    {
        interpretAsCpp = true;
    }
    else
    {
        size_t extensionIndex = inputFileName.find_last_of(".");
        if( extensionIndex != std::string::npos )
        {
            std::string fileExtension = inputFileName.substr( extensionIndex + 1 );
            interpretAsCpp = ( fileExtension == "hpp" ) ||
                             ( fileExtension == "hxx" ) ||
                             ( fileExtension == "hh" );

        }
    }

    Config config( parsedOptions["underlying-typedef"].as<bool>() );

    *output << "// This file has been auto-generated by CppUTestMock. DO NOT EDIT IT!!!" << std::endl;
    *output << std::endl;
    *output << "#include <CppUTestExt/MockSupport.h>" << std::endl;
    if( !interpretAsCpp )
    {
        *output << "extern \"C\" {" << std::endl;
    }
    *output << "#include \"" <<  inputFileName << "\"" << std::endl;
    if( !interpretAsCpp )
    {
        *output << "}" << std::endl;
    }
    *output << std::endl;

    parseFile( inputFileName, config, interpretAsCpp );
}
