/*
 * This file has been auto-generated by CppUMockGen v0.5.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -t "#const CXCursor &=ConstPointer~&$" -t "@std::string=String" -t "#const std::string &=String~$.c_str()"
 */

#include "Constructor.hpp"

#include <CppUTestExt/MockSupport.h>

Constructor::Constructor() noexcept
{
    mock().actualCall("Constructor::Constructor");
}

bool Constructor::IsMockable(const CXCursor & cursor) const noexcept
{
    return mock().actualCall("Constructor::IsMockable").onObject(this).withConstPointerParameter("cursor", &cursor).returnBoolValue();
}

std::string Constructor::GetExpectationFunctionName(const std::string & functionName) const noexcept
{
    return mock().actualCall("Constructor::GetExpectationFunctionName").onObject(this).withStringParameter("functionName", functionName.c_str()).returnStringValue();
}

