/*
 * This file has been auto-generated by CppUTestMock v0.1.0.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

#include "Function.hpp"

#include <CppUTestExt/MockSupport.h>

class Function::Argument
{};

class Function::Return
{};

Function::Function()
: m_isConst( false )
{}

Function::~Function()
{}

bool Function::Parse(const CXCursor & cursor, const Config & config)
{
    return mock().actualCall("Function::Parse").withConstPointerParameter("cursor", &cursor).withConstPointerParameter("config", &config).returnBoolValue();
}

std::string Function::GenerateMock() const
{
    return mock().actualCall("Function::GenerateMock").returnStringValue();
}

bool Function::IsMockable(const CXCursor & cursor) const
{
    return mock().actualCall("Function::IsMockable").withConstPointerParameter("cursor", &cursor).returnBoolValue();
}
