/*
 * This file has been auto-generated by CppUTestMock v0.1.0.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

#include "Method.hpp"

#include <CppUTestExt/MockSupport.h>

Method::Method( const CXCursor &cursor, const Config &config )
: Function( cursor, config )
{
    mock().actualCall("Method::Method").withConstPointerParameter("cursor", &cursor).withConstPointerParameter("config", &config) ;
}

bool Method::IsMockable() const
{
    return mock().actualCall("Method::IsMockable").returnBoolValue();
}

std::string Method::GenerateMock() const
{
    return mock().actualCall("Method::GenerateMock").returnStringValue();
}

