/*
 * This file has been auto-generated by CppUMockGen v0.5.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -t "#const CXCursor &=ConstPointer~&$"
 */

#include "Method.hpp"

#include <CppUTestExt/MockSupport.h>

Method::Method() noexcept
{
    mock().actualCall("Method::Method");
}

bool Method::IsMockable(const CXCursor & cursor) const noexcept
{
    return mock().actualCall("Method::IsMockable").onObject(this).withConstPointerParameter("cursor", &cursor).returnBoolValue();
}

