/*
 * This file has been auto-generated by CppUTestMock v0.3.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -t "#const CXCursor &=ConstPointer/&$" 
 */

#include "Method.hpp"

#include <CppUTestExt/MockSupport.h>

Method::Method() noexcept
{}

bool Method::IsMockable(const CXCursor & cursor) const noexcept
{
    return mock().actualCall("Method::IsMockable").withConstPointerParameter("cursor", &cursor).returnBoolValue();
}

