/*
 * This file has been auto-generated by CppUTestMock v0.1.0.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

#include "MockGenerator.hpp"

#include <CppUTestExt/MockSupport.h>

bool GenerateMock(const std::string & inputFilename, const Config & config, bool interpretAsCpp, const std::vector<std::string> & includePaths, const std::string & genOpts, std::ostream & output, std::ostream & error)
{
    return mock().actualCall("GenerateMock").withStringParameter("inputFilename", inputFilename.c_str()).withConstPointerParameter("config", &config).withBoolParameter("interpretAsCpp", interpretAsCpp).withParameterOfType("std::vector<std::string>", "includePaths", &includePaths).withStringParameter("genOpts", genOpts.c_str()).withOutputParameterOfType("std::ostream", "output", &output).withPointerParameter("error", &error).returnBoolValue();
}

