/*
The MIT License (MIT)

Copyright (c) 2015, by [halex2005](mailto:akharlov@gmail.com)
Copyright (c) 2018, by Jesus Gonzalez <jgonzalez@gdr-sistemas.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#define PRODUCT_VERSION_MAJOR @PRODUCT_VERSION_MAJOR@
#define PRODUCT_VERSION_MINOR @PRODUCT_VERSION_MINOR@
#define PRODUCT_VERSION_PATCH @PRODUCT_VERSION_PATCH@
#define PRODUCT_VERSION_BUILD @PRODUCT_VERSION_BUILD@

#define FILE_VERSION_MAJOR @PRODUCT_VERSION_MAJOR@
#define FILE_VERSION_MINOR @PRODUCT_VERSION_MINOR@
#define FILE_VERSION_PATCH @PRODUCT_VERSION_PATCH@
#define FILE_VERSION_BUILD @PRODUCT_VERSION_BUILD@


#ifndef __TO_STRING
#define __TO_STRING_IMPL(x) #x
#define __TO_STRING(x) __TO_STRING_IMPL(x)
#endif

#define PRODUCT_VERSION_MAJOR_MINOR_STR        __TO_STRING(PRODUCT_VERSION_MAJOR) "." __TO_STRING(PRODUCT_VERSION_MINOR)
#define PRODUCT_VERSION_MAJOR_MINOR_PATCH_STR  PRODUCT_VERSION_MAJOR_MINOR_STR "." __TO_STRING(PRODUCT_VERSION_PATCH)
#define PRODUCT_VERSION_FULL_STR               PRODUCT_VERSION_MAJOR_MINOR_PATCH_STR "." __TO_STRING(PRODUCT_VERSION_BUILD)
#define PRODUCT_VERSION_RESOURCE               PRODUCT_VERSION_MAJOR,PRODUCT_VERSION_MINOR,PRODUCT_VERSION_PATCH,PRODUCT_VERSION_BUILD
#define PRODUCT_VERSION_RESOURCE_STR           PRODUCT_VERSION_FULL_STR "\0"

#define FILE_VERSION_MAJOR_MINOR_STR        __TO_STRING(FILE_VERSION_MAJOR) "." __TO_STRING(FILE_VERSION_MINOR)
#define FILE_VERSION_MAJOR_MINOR_PATCH_STR  FILE_VERSION_MAJOR_MINOR_STR "." __TO_STRING(FILE_VERSION_PATCH)
#define FILE_VERSION_FULL_STR               FILE_VERSION_MAJOR_MINOR_PATCH_STR "." __TO_STRING(FILE_VERSION_BUILD)
#define FILE_VERSION_RESOURCE               FILE_VERSION_MAJOR,FILE_VERSION_MINOR,FILE_VERSION_PATCH,FILE_VERSION_BUILD
#define FILE_VERSION_RESOURCE_STR           FILE_VERSION_FULL_STR "\0"

#define PRODUCT_COMMENTS           "@PRODUCT_COMMENTS@\0"
#define PRODUCT_COMPANY_NAME       "@PRODUCT_COMPANY_NAME@\0"
#define PRODUCT_COMPANY_COPYRIGHT  "@PRODUCT_COMPANY_COPYRIGHT@\0"
#define PRODUCT_FILE_DESCRIPTION   "@PRODUCT_FILE_DESCRIPTION@\0"
#define PRODUCT_INTERNAL_NAME      "@PRODUCT_NAME@\0"
#define PRODUCT_ORIGINAL_FILENAME  "@PRODUCT_ORIGINAL_FILENAME@\0"
#define PRODUCT_BUNDLE             "@PRODUCT_BUNDLE@\0"

#if @PRODUCT_ICON_FLAG@
#define PRODUCT_ICON "@PRODUCT_ICON@"
#endif

#if @PRODUCT_PRIVATE_BUILD_FLAG@
#define VFF_PRIVATE_BUILD          VS_FF_PRIVATEBUILD
#define PRODUCT_PRIVATE_BUILD      "@PRODUCT_PRIVATE_BUILD@\0"
#else
#define VFF_PRIVATE_BUILD          0x0L
#endif

#if @PRODUCT_SPECIAL_BUILD_FLAG@
#define VFF_SPECIAL_BUILD          VS_FF_SPECIALBUILD
#define PRODUCT_SPECIAL_BUILD      "@PRODUCT_SPECIAL_BUILD@\0"
#else
#define VFF_SPECIAL_BUILD          0x0L
#endif

#if @PRODUCT_PRERELEASE_FLAG@
#define VFF_PRERELEASE             VS_FF_PRERELEASE
#else
#define VFF_PRERELEASE             0x0L
#endif

#if @PRODUCT_PATCHED_FLAG@
#define VFF_PATCHED                VS_FF_PATCHED
#else
#define VFF_PATCHED                0x0L
#endif
