function( generate_groups BASE_DIR CURR_DIR )
    string( REPLACE "/" "\\" GROUP_NAME "${CURR_DIR}" )
    source_group( "Source Files\\${GROUP_NAME}" REGULAR_EXPRESSION ${BASE_DIR}/${CURR_DIR}.*\\.cpp )
    source_group( "Header Files\\${GROUP_NAME}" REGULAR_EXPRESSION ${BASE_DIR}/${CURR_DIR}.*\\.h )
    file( GLOB FILE_LIST RELATIVE ${BASE_DIR} ${BASE_DIR}/${CURR_DIR}/* )
    foreach( FILE ${FILE_LIST} )
        if( IS_DIRECTORY ${BASE_DIR}/${FILE} )
            generate_groups( ${BASE_DIR} ${FILE} )
        endif()
    endforeach()
endfunction()